const UPDATE_ROOM = 'UPDATE_ROOM'
const UPDATE_AVAILABLE_ROOMS = 'UPDATE_AVAILABLE_ROOMS'
const UPDATE_ROOM_MESSAGES = 'UPDATE_ROOM_MESSAGES'

module.exports = {
    UPDATE_ROOM,
    UPDATE_AVAILABLE_ROOMS,
    UPDATE_ROOM_MESSAGES,
}
