const UPDATE_CLIPS = 'UPDATE_CLIPS'
const UPDATE_SPEED = 'UPDATE_SPEED'
const UPDATE_CONTENT_ID = 'UPDATE_CONTENT_ID'
const LOGIN = 'LOGIN'
const LOGOUT = 'LOGOUT'
const SET_PLAYLISTS = 'SET_PLAYLISTS'
const SET_PLAYLIST = 'SET_PLAYLIST'
const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN'
const SELECTING_FROM_PLAYLIST = 'SELECTING_FROM_PLAYLIST'
const UPDATE_CLIP = 'UPDATE_CLIP'
const SET_WEB_PANEL_WIDTH = 'SET_WEB_PANEL_WIDTH'
const SET_EDIT_INDEX = 'SET_EDIT_INDEX'
const UPDATE_USER = 'UPDATE_USER'
const SET_VIDEO_PROGRESS = 'SET_VIDEO_PROGRESS'
const ADD_PENDING_CLIP = 'ADD_PENDING_CLIP'
const UPDATE_PENDING_CLIP = 'UPDATE_PENDING_CLIP'
const CLEAR_PENDING = 'CLEAR_PENDING'
const FULFILL_PENDING_CLIP = 'FULFILL_PENDING_CLIP'
const PENDING_DELETE_CLIP = 'PENDING_DELETE_CLIP'
const DELETE_CLIP = 'DELETE_CLIP'
const FULFILL_PENDING_DELETE = 'FULFILL_PENDING_DELETE'
const SET_GOT_SOMETHING_CURSOR = 'SET_GOT_SOMETHING_CURSOR'

module.exports = {
    UPDATE_CLIPS,
    UPDATE_SPEED,
    UPDATE_CONTENT_ID,
    LOGIN,
    LOGOUT,
    SET_PLAYLISTS,
    SET_PLAYLIST,
    SET_ACCESS_TOKEN,
    SELECTING_FROM_PLAYLIST,
    UPDATE_CLIP,
    SET_WEB_PANEL_WIDTH,
    SET_EDIT_INDEX,
    UPDATE_USER,
    SET_VIDEO_PROGRESS,
    ADD_PENDING_CLIP,
    UPDATE_PENDING_CLIP,
    CLEAR_PENDING,
    FULFILL_PENDING_CLIP,
    PENDING_DELETE_CLIP,
    DELETE_CLIP,
    FULFILL_PENDING_DELETE,
    SET_GOT_SOMETHING_CURSOR,
}
