const LOGIN = 'LOGIN'
const LOGOUT = 'LOGOUT'
const UPDATE_USER = 'UPDATE_USER'
const UPDATE_WEB_APP = 'UPDATE_WEB_APP'
const UPDATE_DOMAIN = 'UPDATE_DOMAIN'

module.exports = {
    LOGIN,
    LOGOUT,
    UPDATE_USER,
    UPDATE_WEB_APP,
    UPDATE_DOMAIN,
}
