const UPDATE_CURRENT = 'UPDATE_CURRENT'
const PREP_CAPTURE = 'PREP_CAPTURE'
const UPDATE_OUTPUT_SHAPE = 'UPDATE_OUTPUT_SHAPE'
const UPDATE_APP_OPENED = 'UPDATE_APP_OPENED'

module.exports = {
    UPDATE_CURRENT,
    PREP_CAPTURE,
    UPDATE_OUTPUT_SHAPE,
    UPDATE_APP_OPENED,
}
